server:
  port: 8080

spring:
  datasource:
    username: root
    password: cai123
    url: jdbc:mysql://localhost:3306/address?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  #domain对象的包
  type-aliases-package: com.xmu.address.domain
  #mapper。xml所在的位置
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #自动将SQL中查出来的带下划线的字段，转换为驼峰标志，再去匹配类中的属性
    map-underscore-to-camel-case: true